training:
  batch_size: 2048
  n_epochs: 100000
  n_iters: 200001
  snapshot_freq: 2000
  snapshot_sampling: true
  anneal_power: 2
  log_all_sigmas: true

sampling:
  batch_size: 4096
  data_init: true
  step_lr: 0.00005
  n_steps_each: 10
  ckpt_id: 20000
  final_only: true
  fid: false
  denoise: true
  num_samples4fid: 0
  inpainting: false
  interpolation: true
  n_interpolations: 50

test:
  begin_ckpt: 2000
  end_ckpt: 200000
  batch_size: 4096

data:
  dataset: "Uniform2D"
  data_dim: 2
  support: "[0,1]^2"
  rescaled: false
  num_workers: 2

model:
  sigma_begin: 1.0
  sigma_end: 0.01
  sigma_dist: geometric
  num_classes: 100
  ema: true
  ema_rate: 0.999
  spec_norm: false
  normalization: None
  nonlinearity: swish
  hidden_dim: 256
  n_layers: 4

optim:
  optimizer: "Adam"
  lr: 0.0005
  beta1: 0.9
  beta2: 0.999
  weight_decay: 0.0
  amsgrad: false
  eps: 1e-8
