training:
  batch_size: 2048
  n_epochs: 100000
  n_iters: 200000
  snapshot_freq: 2000
  snapshot_sampling: false
  anneal_power: 2
  log_all_sigmas: true

sampling:
  batch_size: 4096
  data_init: true
  step_lr: 0.00005
  n_steps_each: 10
  ckpt_id: 20000
  final_only: true
  fid: false
  denoise: true
  num_samples4fid: 0
  inpainting: false
  interpolation: true
  n_interpolations: 50

test:
  begin_ckpt: 2000
  end_ckpt: 200000
  batch_size: 4096

data:
  dataset: "Uniform2D"
  data_dim: 2
  support: "[0,1]^2"
  image_size: 1
  channels: 2
  uniform_dequantization: false
  gaussian_dequantization: false
  logit_transform: false
  random_flip: false
  rescaled: false
  num_workers: 2
  n_samples: 100000
  n_test_samples: 5000
  test_seed: 42

model:
  type: mlp
  input_dim: 2
  hidden_dim: 256
  output_dim: 2
  num_layers: 4
  sigma_begin: 1.0
  sigma_end: 0.01
  sigma_dist: geometric
  num_classes: 100
  ema: true
  ema_rate: 0.999
  spec_norm: false
  normalization: None
  nonlinearity: swish

optim:
  optimizer: "Adam"
  lr: 0.0005
  beta1: 0.9
  beta2: 0.999
  weight_decay: 0.0
  amsgrad: false
  eps: 0.0001
